import{a as p}from"./assets/vendor-zu6XShmD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const r={burgerBtnOpenMenu:document.querySelector(".icon-burger"),burgerBtnCloseMenu:document.querySelector(".icon-close"),headerMenuContainer:document.querySelector(".header-menu-container"),menuAnchorAbout:document.querySelector("#menu-anchor-about"),menuAnchorArtists:document.querySelector("#menu-anchor-artists"),menuAnchorReviews:document.querySelector("#menu-anchor-reviews"),artistsGrid:document.getElementById("artists-card-id"),loadMoreBtn:document.getElementById("load-more-btn")};function f(c,t){const o=c.map(s=>{var l;const e=s.strArtistThumb||"https://via.placeholder.com/350x350?text=No+Image",n=((l=s.genres)==null?void 0:l.map(h=>`<li class="genre-tag">${h}</li>`).join(""))||"",a=s.strBiographyEN||"Короткий опис для цього артиста відсутній.";return`
        <li class="artist-card">
          <img src="${e}" alt="${s.strArtist}" class="artist-card-image" />
          <div class="artist-card-content">
            <ul class="artist-card-genres">${n}</ul>
            <h3 class="artist-card-name">${s.strArtist}</h3>
            <p class="artist-card-description">${a}</p>
            <button id="learn-more-btn" class="artist-card-link" data-artist-id="${s._id}">Learn More <svg class="icon-lernmore" width="24" height="24">
      <use href="./img/sprite.svg#icon-caret-arrow-artist-right"></use>
    </svg></button>
          </div>
        </li>
      `}).join("");t.insertAdjacentHTML("beforeend",o)}function g(){r.headerMenuContainer.classList.add("is-open"),window.addEventListener("resize",d),r.menuAnchorAbout.addEventListener("click",i),r.menuAnchorArtists.addEventListener("click",i),r.menuAnchorReviews.addEventListener("click",i)}function i(){r.headerMenuContainer.classList.remove("is-open"),window.removeEventListener("resize",d),r.menuAnchorAbout.removeEventListener("click",i),r.menuAnchorArtists.removeEventListener("click",i),r.menuAnchorReviews.removeEventListener("click",i)}function d(){window.innerWidth>=768&&(r.headerMenuContainer.classList.remove("is-open"),window.removeEventListener("resize",d))}const v="https://sound-wave.b.goit.study/api",y="/artists";async function A(c,t){try{return(await p.get(`${v}${y}`,{params:{page:c,limit:t}})).data.artists||[]}catch(o){return console.error("Не вдалося завантажити артистів:",o),[]}}r.burgerBtnOpenMenu.addEventListener("click",g);r.burgerBtnCloseMenu.addEventListener("click",i);let u=1;const m=8;document.addEventListener("DOMContentLoaded",()=>{const c=r.artistsGrid,t=r.loadMoreBtn;async function o(){t.disabled=!0;const s=document.getElementById("spinner");s.classList.remove("hidden");const e=await A(u,m);s.classList.add("hidden"),e.length>0?(f(e,c),u++,e.length<m?t.style.display="none":t.style.display="flex"):t.style.display="none",t.disabled=!1}t.addEventListener("click",o),o()});
//# sourceMappingURL=index.js.map
