import './js/refs';
import './js/render-functions';
import './js/handlers';
import './js/artists-api';
import './js/helpers';
import './js/mobile-menu';
import './js/feedback';
import './js/artitsts-section';
import './js/artist-modal';
